export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST"
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILED: "GET_ALL_CATEGORIES_FAILED",
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE"
}

export const productConstants = {
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS"
}

export const intialDataConstants = {
    GET_ALL_INITIALDATA_REQUEST: "GET_ALL_INITIALDATA_REQUEST",
    GET_ALL_INITIALDATA_SUCCESS: "GET_ALL_INITIALDATA_SUCCESS",
    GET_ALL_INITIALDATA_FAILURE: "GET_ALL_INITIALDATA_FAILURE"
}